import Head from "next/head";
import Navbar from "@components/Navbar";
import Banner from "@components/Banner";
import {
  fetchActionMovies,
  fetchComedyMovies,
  fetchDocumentries,
  fetchHorrorMovies,
  fetchNetflixOriginals,
  fetchRomanceMovies,
  fetchTopRated,
} from "@/services/movies";
import { useQuery } from "@tanstack/react-query";
import Carousel from "@/components/Carousel";

const Home = () => {
  const { data } = useQuery({
    queryKey: ["netflix-originals"],
    queryFn: fetchNetflixOriginals,
  });

  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black text-white">
        <Navbar />
        {data && (
          <Banner movie={data[Math.floor(Math.random() * data.length - 1)]} />
        )}
        <Carousel
          title="Netflix Originals"
          tileVariant="verticle"
          fetchDataFn={fetchNetflixOriginals}
          queryKey="netflix-originals"
        />
        <Carousel
          title="Top Rated"
          fetchDataFn={fetchTopRated}
          queryKey="top-rated"
        />
        <Carousel
          title="Action Movies"
          fetchDataFn={fetchActionMovies}
          queryKey="action-movies"
        />
        <Carousel
          title="Comedy Movies"
          fetchDataFn={fetchComedyMovies}
          queryKey="comedy-movies"
        />
        <Carousel
          title="Horror Movies"
          fetchDataFn={fetchHorrorMovies}
          queryKey="horror-movies"
        />
        <Carousel
          title="Romance Movies"
          fetchDataFn={fetchRomanceMovies}
          queryKey="romance-movies"
        />
        <Carousel
          title="Documentries"
          fetchDataFn={fetchDocumentries}
          queryKey="documentries"
        />
      </main>
    </>
  );
};

export default Home;
